/*
 * generated by Xtext 2.19.0
 */
package org.integratedmodelling.kap.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.integratedmodelling.kap.parser.antlr.internal.InternalKapParser;
import org.integratedmodelling.kap.services.KapGrammarAccess;

public class KapParser extends AbstractAntlrParser {

	@Inject
	private KapGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalKapParser createParser(XtextTokenStream stream) {
		return new InternalKapParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public KapGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(KapGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
