/*
 * generated by Xtext 2.27.0
 */
package org.integratedmodelling.kdl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.integratedmodelling.kdl.ide.contentassist.antlr.internal.InternalKdlParser;
import org.integratedmodelling.kdl.services.KdlGrammarAccess;

public class KdlParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(KdlGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, KdlGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getModelAccess().getNameAlternatives_0_0_1_0(), "rule__Model__NameAlternatives_0_0_1_0");
			builder.put(grammarAccess.getModelAccess().getPackageAlternatives_0_9_1_0(), "rule__Model__PackageAlternatives_0_9_1_0");
			builder.put(grammarAccess.getActorDefinitionAccess().getAlternatives(), "rule__ActorDefinition__Alternatives");
			builder.put(grammarAccess.getActorDefinitionAccess().getAlternatives_0_1(), "rule__ActorDefinition__Alternatives_0_1");
			builder.put(grammarAccess.getActorDefinitionAccess().getAlternatives_1_5(), "rule__ActorDefinition__Alternatives_1_5");
			builder.put(grammarAccess.getActorDefinitionAccess().getAlternatives_1_5_2_1(), "rule__ActorDefinition__Alternatives_1_5_2_1");
			builder.put(grammarAccess.getActorDefinitionAccess().getNameAlternatives_1_9_0(), "rule__ActorDefinition__NameAlternatives_1_9_0");
			builder.put(grammarAccess.getActorDefinitionAccess().getExtendedAlternatives_1_10_1_0(), "rule__ActorDefinition__ExtendedAlternatives_1_10_1_0");
			builder.put(grammarAccess.getActorDefinitionAccess().getAlternatives_1_15(), "rule__ActorDefinition__Alternatives_1_15");
			builder.put(grammarAccess.getActorDefinitionAccess().getAlternatives_1_15_0(), "rule__ActorDefinition__Alternatives_1_15_0");
			builder.put(grammarAccess.getActorDefinitionAccess().getEnumValuesAlternatives_1_15_1_1_0(), "rule__ActorDefinition__EnumValuesAlternatives_1_15_1_1_0");
			builder.put(grammarAccess.getActorDefinitionAccess().getEnumValuesAlternatives_1_15_1_2_1_0(), "rule__ActorDefinition__EnumValuesAlternatives_1_15_1_2_1_0");
			builder.put(grammarAccess.getDataflowBodyAccess().getJavaClassAlternatives_2_2_1_1_0(), "rule__DataflowBody__JavaClassAlternatives_2_2_1_1_0");
			builder.put(grammarAccess.getGeometryAccess().getAlternatives(), "rule__Geometry__Alternatives");
			builder.put(grammarAccess.getUnitElementAccess().getAlternatives(), "rule__UnitElement__Alternatives");
			builder.put(grammarAccess.getUnitElementAccess().getIdAlternatives_0_0(), "rule__UnitElement__IdAlternatives_0_0");
			builder.put(grammarAccess.getACTORAccess().getAlternatives(), "rule__ACTOR__Alternatives");
			builder.put(grammarAccess.getTARGETAccess().getAlternatives(), "rule__TARGET__Alternatives");
			builder.put(grammarAccess.getClassifierRHSAccess().getAlternatives(), "rule__ClassifierRHS__Alternatives");
			builder.put(grammarAccess.getClassifierRHSAccess().getAlternatives_0(), "rule__ClassifierRHS__Alternatives_0");
			builder.put(grammarAccess.getClassifierRHSAccess().getAlternatives_1_1(), "rule__ClassifierRHS__Alternatives_1_1");
			builder.put(grammarAccess.getClassifierRHSAccess().getAlternatives_1_4(), "rule__ClassifierRHS__Alternatives_1_4");
			builder.put(grammarAccess.getLiteralAccess().getAlternatives(), "rule__Literal__Alternatives");
			builder.put(grammarAccess.getLiteralAccess().getBooleanAlternatives_3_0(), "rule__Literal__BooleanAlternatives_3_0");
			builder.put(grammarAccess.getLiteralOrIdOrCommaAccess().getAlternatives(), "rule__LiteralOrIdOrComma__Alternatives");
			builder.put(grammarAccess.getLiteralOrIdOrCommaAccess().getBooleanAlternatives_3_0(), "rule__LiteralOrIdOrComma__BooleanAlternatives_3_0");
			builder.put(grammarAccess.getLiteralOrIdOrCommaAccess().getIdAlternatives_4_0(), "rule__LiteralOrIdOrComma__IdAlternatives_4_0");
			builder.put(grammarAccess.getLiteralOrIDAccess().getAlternatives(), "rule__LiteralOrID__Alternatives");
			builder.put(grammarAccess.getLiteralOrIDAccess().getBooleanAlternatives_2_0(), "rule__LiteralOrID__BooleanAlternatives_2_0");
			builder.put(grammarAccess.getMetadataAccess().getIdsAlternatives_2_0_0(), "rule__Metadata__IdsAlternatives_2_0_0");
			builder.put(grammarAccess.getMetadataAccess().getValuesAlternatives_2_1_0(), "rule__Metadata__ValuesAlternatives_2_1_0");
			builder.put(grammarAccess.getParameterListAccess().getAlternatives(), "rule__ParameterList__Alternatives");
			builder.put(grammarAccess.getValueAccess().getAlternatives(), "rule__Value__Alternatives");
			builder.put(grammarAccess.getUrnAccess().getNameAlternatives_0(), "rule__Urn__NameAlternatives_0");
			builder.put(grammarAccess.getTableClassifierAccess().getAlternatives(), "rule__TableClassifier__Alternatives");
			builder.put(grammarAccess.getTableClassifierAccess().getAlternatives_0(), "rule__TableClassifier__Alternatives_0");
			builder.put(grammarAccess.getTableClassifierAccess().getAlternatives_1_1(), "rule__TableClassifier__Alternatives_1_1");
			builder.put(grammarAccess.getTableClassifierAccess().getAlternatives_1_4(), "rule__TableClassifier__Alternatives_1_4");
			builder.put(grammarAccess.getLocalFilePathAccess().getAlternatives_0(), "rule__LocalFilePath__Alternatives_0");
			builder.put(grammarAccess.getLocalFilePathAccess().getAlternatives_1_1(), "rule__LocalFilePath__Alternatives_1_1");
			builder.put(grammarAccess.getKeyValuePairAccess().getNameAlternatives_0_0(), "rule__KeyValuePair__NameAlternatives_0_0");
			builder.put(grammarAccess.getKeyValuePairAccess().getAlternatives_1(), "rule__KeyValuePair__Alternatives_1");
			builder.put(grammarAccess.getFunctionAccess().getAlternatives(), "rule__Function__Alternatives");
			builder.put(grammarAccess.getFunctionAccess().getAlternatives_0_0(), "rule__Function__Alternatives_0_0");
			builder.put(grammarAccess.getFunctionAccess().getAlternatives_0_1(), "rule__Function__Alternatives_0_1");
			builder.put(grammarAccess.getREL_OPERATORAccess().getAlternatives(), "rule__REL_OPERATOR__Alternatives");
			builder.put(grammarAccess.getNumberAccess().getAlternatives_0(), "rule__Number__Alternatives_0");
			builder.put(grammarAccess.getNumberAccess().getExponentialAlternatives_3_0_0_0(), "rule__Number__ExponentialAlternatives_3_0_0_0");
			builder.put(grammarAccess.getNumberAccess().getAlternatives_3_0_1(), "rule__Number__Alternatives_3_0_1");
			builder.put(grammarAccess.getPathAccess().getAlternatives_1_0(), "rule__Path__Alternatives_1_0");
			builder.put(grammarAccess.getPropertyIdAccess().getAlternatives_2(), "rule__PropertyId__Alternatives_2");
			builder.put(grammarAccess.getVersionNumberAccess().getAlternatives_3(), "rule__VersionNumber__Alternatives_3");
			builder.put(grammarAccess.getUnitOpAccess().getAlternatives(), "rule__UnitOp__Alternatives");
			builder.put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
			builder.put(grammarAccess.getModelAccess().getGroup_0_0(), "rule__Model__Group_0_0__0");
			builder.put(grammarAccess.getModelAccess().getGroup_0_1(), "rule__Model__Group_0_1__0");
			builder.put(grammarAccess.getModelAccess().getGroup_0_2(), "rule__Model__Group_0_2__0");
			builder.put(grammarAccess.getModelAccess().getGroup_0_3(), "rule__Model__Group_0_3__0");
			builder.put(grammarAccess.getModelAccess().getGroup_0_4(), "rule__Model__Group_0_4__0");
			builder.put(grammarAccess.getModelAccess().getGroup_0_5(), "rule__Model__Group_0_5__0");
			builder.put(grammarAccess.getModelAccess().getGroup_0_6(), "rule__Model__Group_0_6__0");
			builder.put(grammarAccess.getModelAccess().getGroup_0_7(), "rule__Model__Group_0_7__0");
			builder.put(grammarAccess.getModelAccess().getGroup_0_8(), "rule__Model__Group_0_8__0");
			builder.put(grammarAccess.getModelAccess().getGroup_0_9(), "rule__Model__Group_0_9__0");
			builder.put(grammarAccess.getModelAccess().getGroup_0_10(), "rule__Model__Group_0_10__0");
			builder.put(grammarAccess.getModelAccess().getGroup_0_10_2(), "rule__Model__Group_0_10_2__0");
			builder.put(grammarAccess.getModelAccess().getGroup_0_11(), "rule__Model__Group_0_11__0");
			builder.put(grammarAccess.getAnnotationAccess().getGroup(), "rule__Annotation__Group__0");
			builder.put(grammarAccess.getAnnotationAccess().getGroup_1(), "rule__Annotation__Group_1__0");
			builder.put(grammarAccess.getActorDefinitionAccess().getGroup_0(), "rule__ActorDefinition__Group_0__0");
			builder.put(grammarAccess.getActorDefinitionAccess().getGroup_0_5(), "rule__ActorDefinition__Group_0_5__0");
			builder.put(grammarAccess.getActorDefinitionAccess().getGroup_1(), "rule__ActorDefinition__Group_1__0");
			builder.put(grammarAccess.getActorDefinitionAccess().getGroup_1_5_2(), "rule__ActorDefinition__Group_1_5_2__0");
			builder.put(grammarAccess.getActorDefinitionAccess().getGroup_1_5_2_1_1(), "rule__ActorDefinition__Group_1_5_2_1_1__0");
			builder.put(grammarAccess.getActorDefinitionAccess().getGroup_1_10(), "rule__ActorDefinition__Group_1_10__0");
			builder.put(grammarAccess.getActorDefinitionAccess().getGroup_1_11(), "rule__ActorDefinition__Group_1_11__0");
			builder.put(grammarAccess.getActorDefinitionAccess().getGroup_1_11_2(), "rule__ActorDefinition__Group_1_11_2__0");
			builder.put(grammarAccess.getActorDefinitionAccess().getGroup_1_13(), "rule__ActorDefinition__Group_1_13__0");
			builder.put(grammarAccess.getActorDefinitionAccess().getGroup_1_14(), "rule__ActorDefinition__Group_1_14__0");
			builder.put(grammarAccess.getActorDefinitionAccess().getGroup_1_15_0_0(), "rule__ActorDefinition__Group_1_15_0_0__0");
			builder.put(grammarAccess.getActorDefinitionAccess().getGroup_1_15_0_1(), "rule__ActorDefinition__Group_1_15_0_1__0");
			builder.put(grammarAccess.getActorDefinitionAccess().getGroup_1_15_0_2(), "rule__ActorDefinition__Group_1_15_0_2__0");
			builder.put(grammarAccess.getActorDefinitionAccess().getGroup_1_15_1(), "rule__ActorDefinition__Group_1_15_1__0");
			builder.put(grammarAccess.getActorDefinitionAccess().getGroup_1_15_1_2(), "rule__ActorDefinition__Group_1_15_1_2__0");
			builder.put(grammarAccess.getActorDefinitionAccess().getGroup_1_16_0(), "rule__ActorDefinition__Group_1_16_0__0");
			builder.put(grammarAccess.getActorDefinitionAccess().getGroup_1_16_1(), "rule__ActorDefinition__Group_1_16_1__0");
			builder.put(grammarAccess.getActorDefinitionAccess().getGroup_1_17(), "rule__ActorDefinition__Group_1_17__0");
			builder.put(grammarAccess.getActorDefinitionAccess().getGroup_1_18(), "rule__ActorDefinition__Group_1_18__0");
			builder.put(grammarAccess.getActorDefinitionAccess().getGroup_1_18_2(), "rule__ActorDefinition__Group_1_18_2__0");
			builder.put(grammarAccess.getDataflowBodyAccess().getGroup(), "rule__DataflowBody__Group__0");
			builder.put(grammarAccess.getDataflowBodyAccess().getGroup_2_0(), "rule__DataflowBody__Group_2_0__0");
			builder.put(grammarAccess.getDataflowBodyAccess().getGroup_2_2(), "rule__DataflowBody__Group_2_2__0");
			builder.put(grammarAccess.getDataflowBodyAccess().getGroup_2_2_0(), "rule__DataflowBody__Group_2_2_0__0");
			builder.put(grammarAccess.getDataflowBodyAccess().getGroup_2_2_1(), "rule__DataflowBody__Group_2_2_1__0");
			builder.put(grammarAccess.getComputationAccess().getGroup(), "rule__Computation__Group__0");
			builder.put(grammarAccess.getComputationAccess().getGroup_2(), "rule__Computation__Group_2__0");
			builder.put(grammarAccess.getGeometryAccess().getGroup_1(), "rule__Geometry__Group_1__0");
			builder.put(grammarAccess.getGeometryAccess().getGroup_1_1(), "rule__Geometry__Group_1_1__0");
			builder.put(grammarAccess.getParameterAccess().getGroup(), "rule__Parameter__Group__0");
			builder.put(grammarAccess.getUnitElementAccess().getGroup_1(), "rule__UnitElement__Group_1__0");
			builder.put(grammarAccess.getUnitAccess().getGroup(), "rule__Unit__Group__0");
			builder.put(grammarAccess.getUnitAccess().getGroup_2(), "rule__Unit__Group_2__0");
			builder.put(grammarAccess.getUnitAccess().getGroup_2_0(), "rule__Unit__Group_2_0__0");
			builder.put(grammarAccess.getCurrencyAccess().getGroup(), "rule__Currency__Group__0");
			builder.put(grammarAccess.getCurrencyAccess().getGroup_1(), "rule__Currency__Group_1__0");
			builder.put(grammarAccess.getCurrencyAccess().getGroup_2(), "rule__Currency__Group_2__0");
			builder.put(grammarAccess.getClassifierRHSAccess().getGroup_1(), "rule__ClassifierRHS__Group_1__0");
			builder.put(grammarAccess.getClassifierRHSAccess().getGroup_3(), "rule__ClassifierRHS__Group_3__0");
			builder.put(grammarAccess.getClassifierRHSAccess().getGroup_6(), "rule__ClassifierRHS__Group_6__0");
			builder.put(grammarAccess.getClassifierRHSAccess().getGroup_6_2(), "rule__ClassifierRHS__Group_6_2__0");
			builder.put(grammarAccess.getClassifierRHSAccess().getGroup_7(), "rule__ClassifierRHS__Group_7__0");
			builder.put(grammarAccess.getListAccess().getGroup(), "rule__List__Group__0");
			builder.put(grammarAccess.getLiteralAccess().getGroup_1(), "rule__Literal__Group_1__0");
			builder.put(grammarAccess.getLiteralOrIdOrCommaAccess().getGroup_0(), "rule__LiteralOrIdOrComma__Group_0__0");
			builder.put(grammarAccess.getMetadataAccess().getGroup(), "rule__Metadata__Group__0");
			builder.put(grammarAccess.getMetadataAccess().getGroup_2(), "rule__Metadata__Group_2__0");
			builder.put(grammarAccess.getParameterListAccess().getGroup_0(), "rule__ParameterList__Group_0__0");
			builder.put(grammarAccess.getParameterListAccess().getGroup_0_1(), "rule__ParameterList__Group_0_1__0");
			builder.put(grammarAccess.getParameterListAccess().getGroup_1(), "rule__ParameterList__Group_1__0");
			builder.put(grammarAccess.getParameterListAccess().getGroup_1_1(), "rule__ParameterList__Group_1_1__0");
			builder.put(grammarAccess.getDefineAccess().getGroup(), "rule__Define__Group__0");
			builder.put(grammarAccess.getUrnIdAccess().getGroup(), "rule__UrnId__Group__0");
			builder.put(grammarAccess.getUrnIdAccess().getGroup_8(), "rule__UrnId__Group_8__0");
			builder.put(grammarAccess.getUrnIdAccess().getGroup_9(), "rule__UrnId__Group_9__0");
			builder.put(grammarAccess.getMapAccess().getGroup(), "rule__Map__Group__0");
			builder.put(grammarAccess.getMapAccess().getGroup_2(), "rule__Map__Group_2__0");
			builder.put(grammarAccess.getMapAccess().getGroup_2_1(), "rule__Map__Group_2_1__0");
			builder.put(grammarAccess.getMapAccess().getGroup_2_1_0(), "rule__Map__Group_2_1_0__0");
			builder.put(grammarAccess.getMapEntryAccess().getGroup(), "rule__MapEntry__Group__0");
			builder.put(grammarAccess.getLookupTableAccess().getGroup(), "rule__LookupTable__Group__0");
			builder.put(grammarAccess.getTableAccess().getGroup(), "rule__Table__Group__0");
			builder.put(grammarAccess.getTableAccess().getGroup_1(), "rule__Table__Group_1__0");
			builder.put(grammarAccess.getTableRowAccess().getGroup(), "rule__TableRow__Group__0");
			builder.put(grammarAccess.getTableRowAccess().getGroup_1(), "rule__TableRow__Group_1__0");
			builder.put(grammarAccess.getTableClassifierAccess().getGroup_1(), "rule__TableClassifier__Group_1__0");
			builder.put(grammarAccess.getTableClassifierAccess().getGroup_3(), "rule__TableClassifier__Group_3__0");
			builder.put(grammarAccess.getTableClassifierAccess().getGroup_5(), "rule__TableClassifier__Group_5__0");
			builder.put(grammarAccess.getLocalFilePathAccess().getGroup(), "rule__LocalFilePath__Group__0");
			builder.put(grammarAccess.getLocalFilePathAccess().getGroup_1(), "rule__LocalFilePath__Group_1__0");
			builder.put(grammarAccess.getLocalFilePathAccess().getGroup_2(), "rule__LocalFilePath__Group_2__0");
			builder.put(grammarAccess.getLocalFilePathAccess().getGroup_3(), "rule__LocalFilePath__Group_3__0");
			builder.put(grammarAccess.getKeyValuePairAccess().getGroup(), "rule__KeyValuePair__Group__0");
			builder.put(grammarAccess.getFunctionAccess().getGroup_0(), "rule__Function__Group_0__0");
			builder.put(grammarAccess.getFunctionAccess().getGroup_0_0_0(), "rule__Function__Group_0_0_0__0");
			builder.put(grammarAccess.getFunctionAccess().getGroup_0_0_1(), "rule__Function__Group_0_0_1__0");
			builder.put(grammarAccess.getFunctionAccess().getGroup_0_1_0(), "rule__Function__Group_0_1_0__0");
			builder.put(grammarAccess.getFunctionAccess().getGroup_0_2(), "rule__Function__Group_0_2__0");
			builder.put(grammarAccess.getFunctionAccess().getGroup_1(), "rule__Function__Group_1__0");
			builder.put(grammarAccess.getFunctionAccess().getGroup_1_2(), "rule__Function__Group_1_2__0");
			builder.put(grammarAccess.getNumberAccess().getGroup(), "rule__Number__Group__0");
			builder.put(grammarAccess.getNumberAccess().getGroup_2(), "rule__Number__Group_2__0");
			builder.put(grammarAccess.getNumberAccess().getGroup_2_0(), "rule__Number__Group_2_0__0");
			builder.put(grammarAccess.getNumberAccess().getGroup_3(), "rule__Number__Group_3__0");
			builder.put(grammarAccess.getNumberAccess().getGroup_3_0(), "rule__Number__Group_3_0__0");
			builder.put(grammarAccess.getPathNameAccess().getGroup(), "rule__PathName__Group__0");
			builder.put(grammarAccess.getPathNameAccess().getGroup_1(), "rule__PathName__Group_1__0");
			builder.put(grammarAccess.getPathAccess().getGroup(), "rule__Path__Group__0");
			builder.put(grammarAccess.getPathAccess().getGroup_1(), "rule__Path__Group_1__0");
			builder.put(grammarAccess.getJavaClassAccess().getGroup(), "rule__JavaClass__Group__0");
			builder.put(grammarAccess.getNamespaceIdAccess().getGroup(), "rule__NamespaceId__Group__0");
			builder.put(grammarAccess.getPropertyIdAccess().getGroup(), "rule__PropertyId__Group__0");
			builder.put(grammarAccess.getVersionNumberAccess().getGroup(), "rule__VersionNumber__Group__0");
			builder.put(grammarAccess.getVersionNumberAccess().getGroup_1(), "rule__VersionNumber__Group_1__0");
			builder.put(grammarAccess.getVersionNumberAccess().getGroup_1_2(), "rule__VersionNumber__Group_1_2__0");
			builder.put(grammarAccess.getModelAccess().getNameAssignment_0_0_1(), "rule__Model__NameAssignment_0_0_1");
			builder.put(grammarAccess.getModelAccess().getVariablesAssignment_0_1_1(), "rule__Model__VariablesAssignment_0_1_1");
			builder.put(grammarAccess.getModelAccess().getConstantsAssignment_0_2_1(), "rule__Model__ConstantsAssignment_0_2_1");
			builder.put(grammarAccess.getModelAccess().getAuthorsAssignment_0_3_1(), "rule__Model__AuthorsAssignment_0_3_1");
			builder.put(grammarAccess.getModelAccess().getVersionAssignment_0_4_1(), "rule__Model__VersionAssignment_0_4_1");
			builder.put(grammarAccess.getModelAccess().getKlabVersionAssignment_0_5_1(), "rule__Model__KlabVersionAssignment_0_5_1");
			builder.put(grammarAccess.getModelAccess().getWorldviewAssignment_0_6_1(), "rule__Model__WorldviewAssignment_0_6_1");
			builder.put(grammarAccess.getModelAccess().getGeometryAssignment_0_7_1(), "rule__Model__GeometryAssignment_0_7_1");
			builder.put(grammarAccess.getModelAccess().getEndpointAssignment_0_8_1(), "rule__Model__EndpointAssignment_0_8_1");
			builder.put(grammarAccess.getModelAccess().getPackageAssignment_0_9_1(), "rule__Model__PackageAssignment_0_9_1");
			builder.put(grammarAccess.getModelAccess().getScaleAssignment_0_10_1(), "rule__Model__ScaleAssignment_0_10_1");
			builder.put(grammarAccess.getModelAccess().getScaleAssignment_0_10_2_1(), "rule__Model__ScaleAssignment_0_10_2_1");
			builder.put(grammarAccess.getModelAccess().getContextUrnAssignment_0_11_1(), "rule__Model__ContextUrnAssignment_0_11_1");
			builder.put(grammarAccess.getModelAccess().getDefinesAssignment_1(), "rule__Model__DefinesAssignment_1");
			builder.put(grammarAccess.getModelAccess().getActorsAssignment_2(), "rule__Model__ActorsAssignment_2");
			builder.put(grammarAccess.getAnnotationAccess().getNameAssignment_0(), "rule__Annotation__NameAssignment_0");
			builder.put(grammarAccess.getAnnotationAccess().getParametersAssignment_1_1(), "rule__Annotation__ParametersAssignment_1_1");
			builder.put(grammarAccess.getActorDefinitionAccess().getConstAssignment_0_0(), "rule__ActorDefinition__ConstAssignment_0_0");
			builder.put(grammarAccess.getActorDefinitionAccess().getExportedAssignment_0_1_0(), "rule__ActorDefinition__ExportedAssignment_0_1_0");
			builder.put(grammarAccess.getActorDefinitionAccess().getImportedAssignment_0_1_1(), "rule__ActorDefinition__ImportedAssignment_0_1_1");
			builder.put(grammarAccess.getActorDefinitionAccess().getTypeAssignment_0_2(), "rule__ActorDefinition__TypeAssignment_0_2");
			builder.put(grammarAccess.getActorDefinitionAccess().getAnnotationTagAssignment_0_3(), "rule__ActorDefinition__AnnotationTagAssignment_0_3");
			builder.put(grammarAccess.getActorDefinitionAccess().getDocstringAssignment_0_4(), "rule__ActorDefinition__DocstringAssignment_0_4");
			builder.put(grammarAccess.getActorDefinitionAccess().getLabelAssignment_0_5_1(), "rule__ActorDefinition__LabelAssignment_0_5_1");
			builder.put(grammarAccess.getActorDefinitionAccess().getAnnotationsAssignment_1_0(), "rule__ActorDefinition__AnnotationsAssignment_1_0");
			builder.put(grammarAccess.getActorDefinitionAccess().getAbstractAssignment_1_1(), "rule__ActorDefinition__AbstractAssignment_1_1");
			builder.put(grammarAccess.getActorDefinitionAccess().getConstAssignment_1_2(), "rule__ActorDefinition__ConstAssignment_1_2");
			builder.put(grammarAccess.getActorDefinitionAccess().getFinalAssignment_1_3(), "rule__ActorDefinition__FinalAssignment_1_3");
			builder.put(grammarAccess.getActorDefinitionAccess().getOptionalAssignment_1_4(), "rule__ActorDefinition__OptionalAssignment_1_4");
			builder.put(grammarAccess.getActorDefinitionAccess().getExportedAssignment_1_5_0(), "rule__ActorDefinition__ExportedAssignment_1_5_0");
			builder.put(grammarAccess.getActorDefinitionAccess().getFilterAssignment_1_5_1(), "rule__ActorDefinition__FilterAssignment_1_5_1");
			builder.put(grammarAccess.getActorDefinitionAccess().getImportedAssignment_1_5_2_0(), "rule__ActorDefinition__ImportedAssignment_1_5_2_0");
			builder.put(grammarAccess.getActorDefinitionAccess().getMultipleAssignment_1_5_2_1_0(), "rule__ActorDefinition__MultipleAssignment_1_5_2_1_0");
			builder.put(grammarAccess.getActorDefinitionAccess().getArityAssignment_1_5_2_1_1_0(), "rule__ActorDefinition__ArityAssignment_1_5_2_1_1_0");
			builder.put(grammarAccess.getActorDefinitionAccess().getMinimumAssignment_1_5_2_1_1_1(), "rule__ActorDefinition__MinimumAssignment_1_5_2_1_1_1");
			builder.put(grammarAccess.getActorDefinitionAccess().getParameterAssignment_1_6(), "rule__ActorDefinition__ParameterAssignment_1_6");
			builder.put(grammarAccess.getActorDefinitionAccess().getTypeAssignment_1_7(), "rule__ActorDefinition__TypeAssignment_1_7");
			builder.put(grammarAccess.getActorDefinitionAccess().getExpressionAssignment_1_8(), "rule__ActorDefinition__ExpressionAssignment_1_8");
			builder.put(grammarAccess.getActorDefinitionAccess().getNameAssignment_1_9(), "rule__ActorDefinition__NameAssignment_1_9");
			builder.put(grammarAccess.getActorDefinitionAccess().getExtendedAssignment_1_10_1(), "rule__ActorDefinition__ExtendedAssignment_1_10_1");
			builder.put(grammarAccess.getActorDefinitionAccess().getTargetsAssignment_1_11_1(), "rule__ActorDefinition__TargetsAssignment_1_11_1");
			builder.put(grammarAccess.getActorDefinitionAccess().getTargetsAssignment_1_11_2_1(), "rule__ActorDefinition__TargetsAssignment_1_11_2_1");
			builder.put(grammarAccess.getActorDefinitionAccess().getDocstringAssignment_1_12(), "rule__ActorDefinition__DocstringAssignment_1_12");
			builder.put(grammarAccess.getActorDefinitionAccess().getLabelAssignment_1_13_1(), "rule__ActorDefinition__LabelAssignment_1_13_1");
			builder.put(grammarAccess.getActorDefinitionAccess().getBodyAssignment_1_14_1(), "rule__ActorDefinition__BodyAssignment_1_14_1");
			builder.put(grammarAccess.getActorDefinitionAccess().getRangeMinAssignment_1_15_0_0_1(), "rule__ActorDefinition__RangeMinAssignment_1_15_0_0_1");
			builder.put(grammarAccess.getActorDefinitionAccess().getRangeMaxAssignment_1_15_0_1_1(), "rule__ActorDefinition__RangeMaxAssignment_1_15_0_1_1");
			builder.put(grammarAccess.getActorDefinitionAccess().getRangeMinAssignment_1_15_0_2_1(), "rule__ActorDefinition__RangeMinAssignment_1_15_0_2_1");
			builder.put(grammarAccess.getActorDefinitionAccess().getRangeMaxAssignment_1_15_0_2_3(), "rule__ActorDefinition__RangeMaxAssignment_1_15_0_2_3");
			builder.put(grammarAccess.getActorDefinitionAccess().getEnumValuesAssignment_1_15_1_1(), "rule__ActorDefinition__EnumValuesAssignment_1_15_1_1");
			builder.put(grammarAccess.getActorDefinitionAccess().getEnumValuesAssignment_1_15_1_2_1(), "rule__ActorDefinition__EnumValuesAssignment_1_15_1_2_1");
			builder.put(grammarAccess.getActorDefinitionAccess().getDefaultAssignment_1_16_0_1(), "rule__ActorDefinition__DefaultAssignment_1_16_0_1");
			builder.put(grammarAccess.getActorDefinitionAccess().getUnitAssignment_1_16_1_1(), "rule__ActorDefinition__UnitAssignment_1_16_1_1");
			builder.put(grammarAccess.getActorDefinitionAccess().getLocalNameAssignment_1_17_1(), "rule__ActorDefinition__LocalNameAssignment_1_17_1");
			builder.put(grammarAccess.getActorDefinitionAccess().getCoverageAssignment_1_18_1(), "rule__ActorDefinition__CoverageAssignment_1_18_1");
			builder.put(grammarAccess.getActorDefinitionAccess().getCoverageAssignment_1_18_2_1(), "rule__ActorDefinition__CoverageAssignment_1_18_2_1");
			builder.put(grammarAccess.getDataflowBodyAccess().getDataflowsAssignment_1(), "rule__DataflowBody__DataflowsAssignment_1");
			builder.put(grammarAccess.getDataflowBodyAccess().getGeometryAssignment_2_0_1(), "rule__DataflowBody__GeometryAssignment_2_0_1");
			builder.put(grammarAccess.getDataflowBodyAccess().getComputationsAssignment_2_1(), "rule__DataflowBody__ComputationsAssignment_2_1");
			builder.put(grammarAccess.getDataflowBodyAccess().getMetadataAssignment_2_2_0_1(), "rule__DataflowBody__MetadataAssignment_2_2_0_1");
			builder.put(grammarAccess.getDataflowBodyAccess().getJavaClassAssignment_2_2_1_1(), "rule__DataflowBody__JavaClassAssignment_2_2_1_1");
			builder.put(grammarAccess.getComputationAccess().getFunctionsAssignment_1(), "rule__Computation__FunctionsAssignment_1");
			builder.put(grammarAccess.getComputationAccess().getFunctionsAssignment_2_1(), "rule__Computation__FunctionsAssignment_2_1");
			builder.put(grammarAccess.getParameterAccess().getNameAssignment_0(), "rule__Parameter__NameAssignment_0");
			builder.put(grammarAccess.getParameterAccess().getValueAssignment_1(), "rule__Parameter__ValueAssignment_1");
			builder.put(grammarAccess.getParameterAccess().getDocstringAssignment_2(), "rule__Parameter__DocstringAssignment_2");
			builder.put(grammarAccess.getUnitElementAccess().getIdAssignment_0(), "rule__UnitElement__IdAssignment_0");
			builder.put(grammarAccess.getUnitElementAccess().getUnitAssignment_1_1(), "rule__UnitElement__UnitAssignment_1_1");
			builder.put(grammarAccess.getUnitAccess().getRootAssignment_1(), "rule__Unit__RootAssignment_1");
			builder.put(grammarAccess.getUnitAccess().getConnectorsAssignment_2_0_0(), "rule__Unit__ConnectorsAssignment_2_0_0");
			builder.put(grammarAccess.getUnitAccess().getUnitsAssignment_2_1(), "rule__Unit__UnitsAssignment_2_1");
			builder.put(grammarAccess.getCurrencyAccess().getIdAssignment_0(), "rule__Currency__IdAssignment_0");
			builder.put(grammarAccess.getCurrencyAccess().getYearAssignment_1_1(), "rule__Currency__YearAssignment_1_1");
			builder.put(grammarAccess.getCurrencyAccess().getUnitsAssignment_2_1(), "rule__Currency__UnitsAssignment_2_1");
			builder.put(grammarAccess.getClassifierRHSAccess().getBooleanAssignment_0_0(), "rule__ClassifierRHS__BooleanAssignment_0_0");
			builder.put(grammarAccess.getClassifierRHSAccess().getBooleanAssignment_0_1(), "rule__ClassifierRHS__BooleanAssignment_0_1");
			builder.put(grammarAccess.getClassifierRHSAccess().getInt0Assignment_1_0(), "rule__ClassifierRHS__Int0Assignment_1_0");
			builder.put(grammarAccess.getClassifierRHSAccess().getLeftLimitAssignment_1_1_0(), "rule__ClassifierRHS__LeftLimitAssignment_1_1_0");
			builder.put(grammarAccess.getClassifierRHSAccess().getInt1Assignment_1_3(), "rule__ClassifierRHS__Int1Assignment_1_3");
			builder.put(grammarAccess.getClassifierRHSAccess().getRightLimitAssignment_1_4_0(), "rule__ClassifierRHS__RightLimitAssignment_1_4_0");
			builder.put(grammarAccess.getClassifierRHSAccess().getNumAssignment_2(), "rule__ClassifierRHS__NumAssignment_2");
			builder.put(grammarAccess.getClassifierRHSAccess().getSetAssignment_3_1(), "rule__ClassifierRHS__SetAssignment_3_1");
			builder.put(grammarAccess.getClassifierRHSAccess().getStringAssignment_4(), "rule__ClassifierRHS__StringAssignment_4");
			builder.put(grammarAccess.getClassifierRHSAccess().getMapAssignment_5(), "rule__ClassifierRHS__MapAssignment_5");
			builder.put(grammarAccess.getClassifierRHSAccess().getToResolveAssignment_6_1(), "rule__ClassifierRHS__ToResolveAssignment_6_1");
			builder.put(grammarAccess.getClassifierRHSAccess().getToResolveAssignment_6_2_1(), "rule__ClassifierRHS__ToResolveAssignment_6_2_1");
			builder.put(grammarAccess.getClassifierRHSAccess().getOpAssignment_7_0(), "rule__ClassifierRHS__OpAssignment_7_0");
			builder.put(grammarAccess.getClassifierRHSAccess().getExpressionAssignment_7_1(), "rule__ClassifierRHS__ExpressionAssignment_7_1");
			builder.put(grammarAccess.getClassifierRHSAccess().getNodataAssignment_8(), "rule__ClassifierRHS__NodataAssignment_8");
			builder.put(grammarAccess.getClassifierRHSAccess().getStarAssignment_9(), "rule__ClassifierRHS__StarAssignment_9");
			builder.put(grammarAccess.getListAccess().getContentsAssignment_2(), "rule__List__ContentsAssignment_2");
			builder.put(grammarAccess.getLiteralAccess().getNumberAssignment_0(), "rule__Literal__NumberAssignment_0");
			builder.put(grammarAccess.getLiteralAccess().getFromAssignment_1_0(), "rule__Literal__FromAssignment_1_0");
			builder.put(grammarAccess.getLiteralAccess().getToAssignment_1_2(), "rule__Literal__ToAssignment_1_2");
			builder.put(grammarAccess.getLiteralAccess().getStringAssignment_2(), "rule__Literal__StringAssignment_2");
			builder.put(grammarAccess.getLiteralAccess().getBooleanAssignment_3(), "rule__Literal__BooleanAssignment_3");
			builder.put(grammarAccess.getLiteralOrIdOrCommaAccess().getFromAssignment_0_0(), "rule__LiteralOrIdOrComma__FromAssignment_0_0");
			builder.put(grammarAccess.getLiteralOrIdOrCommaAccess().getToAssignment_0_2(), "rule__LiteralOrIdOrComma__ToAssignment_0_2");
			builder.put(grammarAccess.getLiteralOrIdOrCommaAccess().getNumberAssignment_1(), "rule__LiteralOrIdOrComma__NumberAssignment_1");
			builder.put(grammarAccess.getLiteralOrIdOrCommaAccess().getStringAssignment_2(), "rule__LiteralOrIdOrComma__StringAssignment_2");
			builder.put(grammarAccess.getLiteralOrIdOrCommaAccess().getBooleanAssignment_3(), "rule__LiteralOrIdOrComma__BooleanAssignment_3");
			builder.put(grammarAccess.getLiteralOrIdOrCommaAccess().getIdAssignment_4(), "rule__LiteralOrIdOrComma__IdAssignment_4");
			builder.put(grammarAccess.getLiteralOrIdOrCommaAccess().getCommaAssignment_5(), "rule__LiteralOrIdOrComma__CommaAssignment_5");
			builder.put(grammarAccess.getLiteralOrIDAccess().getNumberAssignment_0(), "rule__LiteralOrID__NumberAssignment_0");
			builder.put(grammarAccess.getLiteralOrIDAccess().getStringAssignment_1(), "rule__LiteralOrID__StringAssignment_1");
			builder.put(grammarAccess.getLiteralOrIDAccess().getBooleanAssignment_2(), "rule__LiteralOrID__BooleanAssignment_2");
			builder.put(grammarAccess.getLiteralOrIDAccess().getIdAssignment_3(), "rule__LiteralOrID__IdAssignment_3");
			builder.put(grammarAccess.getMetadataAccess().getIdsAssignment_2_0(), "rule__Metadata__IdsAssignment_2_0");
			builder.put(grammarAccess.getMetadataAccess().getValuesAssignment_2_1(), "rule__Metadata__ValuesAssignment_2_1");
			builder.put(grammarAccess.getParameterListAccess().getValuesAssignment_0_0(), "rule__ParameterList__ValuesAssignment_0_0");
			builder.put(grammarAccess.getParameterListAccess().getValuesAssignment_0_1_1(), "rule__ParameterList__ValuesAssignment_0_1_1");
			builder.put(grammarAccess.getParameterListAccess().getPairsAssignment_1_0(), "rule__ParameterList__PairsAssignment_1_0");
			builder.put(grammarAccess.getParameterListAccess().getPairsAssignment_1_1_1(), "rule__ParameterList__PairsAssignment_1_1_1");
			builder.put(grammarAccess.getValueAccess().getLiteralAssignment_0(), "rule__Value__LiteralAssignment_0");
			builder.put(grammarAccess.getValueAccess().getFunctionAssignment_1(), "rule__Value__FunctionAssignment_1");
			builder.put(grammarAccess.getValueAccess().getUrnAssignment_2(), "rule__Value__UrnAssignment_2");
			builder.put(grammarAccess.getValueAccess().getListAssignment_3(), "rule__Value__ListAssignment_3");
			builder.put(grammarAccess.getValueAccess().getMapAssignment_4(), "rule__Value__MapAssignment_4");
			builder.put(grammarAccess.getValueAccess().getExpressionAssignment_5(), "rule__Value__ExpressionAssignment_5");
			builder.put(grammarAccess.getValueAccess().getTableAssignment_6(), "rule__Value__TableAssignment_6");
			builder.put(grammarAccess.getValueAccess().getEnumIdAssignment_7(), "rule__Value__EnumIdAssignment_7");
			builder.put(grammarAccess.getDefineAccess().getClassAssignment_1(), "rule__Define__ClassAssignment_1");
			builder.put(grammarAccess.getDefineAccess().getNameAssignment_2(), "rule__Define__NameAssignment_2");
			builder.put(grammarAccess.getDefineAccess().getValueAssignment_4(), "rule__Define__ValueAssignment_4");
			builder.put(grammarAccess.getUrnAccess().getNameAssignment(), "rule__Urn__NameAssignment");
			builder.put(grammarAccess.getMapAccess().getEntriesAssignment_2_0(), "rule__Map__EntriesAssignment_2_0");
			builder.put(grammarAccess.getMapAccess().getEntriesAssignment_2_1_1(), "rule__Map__EntriesAssignment_2_1_1");
			builder.put(grammarAccess.getMapEntryAccess().getClassifierAssignment_0(), "rule__MapEntry__ClassifierAssignment_0");
			builder.put(grammarAccess.getMapEntryAccess().getValueAssignment_2(), "rule__MapEntry__ValueAssignment_2");
			builder.put(grammarAccess.getLookupTableAccess().getTableAssignment_2(), "rule__LookupTable__TableAssignment_2");
			builder.put(grammarAccess.getTableAccess().getRowsAssignment_0(), "rule__Table__RowsAssignment_0");
			builder.put(grammarAccess.getTableAccess().getRowsAssignment_1_1(), "rule__Table__RowsAssignment_1_1");
			builder.put(grammarAccess.getTableRowAccess().getElementsAssignment_0(), "rule__TableRow__ElementsAssignment_0");
			builder.put(grammarAccess.getTableRowAccess().getElementsAssignment_1_1(), "rule__TableRow__ElementsAssignment_1_1");
			builder.put(grammarAccess.getTableClassifierAccess().getBooleanAssignment_0_0(), "rule__TableClassifier__BooleanAssignment_0_0");
			builder.put(grammarAccess.getTableClassifierAccess().getBooleanAssignment_0_1(), "rule__TableClassifier__BooleanAssignment_0_1");
			builder.put(grammarAccess.getTableClassifierAccess().getInt0Assignment_1_0(), "rule__TableClassifier__Int0Assignment_1_0");
			builder.put(grammarAccess.getTableClassifierAccess().getLeftLimitAssignment_1_1_0(), "rule__TableClassifier__LeftLimitAssignment_1_1_0");
			builder.put(grammarAccess.getTableClassifierAccess().getInt1Assignment_1_3(), "rule__TableClassifier__Int1Assignment_1_3");
			builder.put(grammarAccess.getTableClassifierAccess().getRightLimitAssignment_1_4_0(), "rule__TableClassifier__RightLimitAssignment_1_4_0");
			builder.put(grammarAccess.getTableClassifierAccess().getNumAssignment_2(), "rule__TableClassifier__NumAssignment_2");
			builder.put(grammarAccess.getTableClassifierAccess().getSetAssignment_3_1(), "rule__TableClassifier__SetAssignment_3_1");
			builder.put(grammarAccess.getTableClassifierAccess().getStringAssignment_4(), "rule__TableClassifier__StringAssignment_4");
			builder.put(grammarAccess.getTableClassifierAccess().getOpAssignment_5_0(), "rule__TableClassifier__OpAssignment_5_0");
			builder.put(grammarAccess.getTableClassifierAccess().getExpressionAssignment_5_1(), "rule__TableClassifier__ExpressionAssignment_5_1");
			builder.put(grammarAccess.getTableClassifierAccess().getExprAssignment_6(), "rule__TableClassifier__ExprAssignment_6");
			builder.put(grammarAccess.getTableClassifierAccess().getNodataAssignment_7(), "rule__TableClassifier__NodataAssignment_7");
			builder.put(grammarAccess.getTableClassifierAccess().getStarAssignment_8(), "rule__TableClassifier__StarAssignment_8");
			builder.put(grammarAccess.getTableClassifierAccess().getAnythingAssignment_9(), "rule__TableClassifier__AnythingAssignment_9");
			builder.put(grammarAccess.getKeyValuePairAccess().getNameAssignment_0(), "rule__KeyValuePair__NameAssignment_0");
			builder.put(grammarAccess.getKeyValuePairAccess().getInteractiveAssignment_1_0(), "rule__KeyValuePair__InteractiveAssignment_1_0");
			builder.put(grammarAccess.getKeyValuePairAccess().getValueAssignment_2(), "rule__KeyValuePair__ValueAssignment_2");
			builder.put(grammarAccess.getFunctionAccess().getMediatedAssignment_0_0_0_0(), "rule__Function__MediatedAssignment_0_0_0_0");
			builder.put(grammarAccess.getFunctionAccess().getVariableAssignment_0_0_1_0(), "rule__Function__VariableAssignment_0_0_1_0");
			builder.put(grammarAccess.getFunctionAccess().getNameAssignment_0_1_0_0(), "rule__Function__NameAssignment_0_1_0_0");
			builder.put(grammarAccess.getFunctionAccess().getParametersAssignment_0_1_0_2(), "rule__Function__ParametersAssignment_0_1_0_2");
			builder.put(grammarAccess.getFunctionAccess().getUrnAssignment_0_1_1(), "rule__Function__UrnAssignment_0_1_1");
			builder.put(grammarAccess.getFunctionAccess().getValueAssignment_0_1_2(), "rule__Function__ValueAssignment_0_1_2");
			builder.put(grammarAccess.getFunctionAccess().getExpressionAssignment_0_1_3(), "rule__Function__ExpressionAssignment_0_1_3");
			builder.put(grammarAccess.getFunctionAccess().getTargetAssignment_0_2_1(), "rule__Function__TargetAssignment_0_2_1");
			builder.put(grammarAccess.getFunctionAccess().getChainAssignment_1_1(), "rule__Function__ChainAssignment_1_1");
			builder.put(grammarAccess.getFunctionAccess().getChainAssignment_1_2_1(), "rule__Function__ChainAssignment_1_2_1");
			builder.put(grammarAccess.getREL_OPERATORAccess().getGtAssignment_0(), "rule__REL_OPERATOR__GtAssignment_0");
			builder.put(grammarAccess.getREL_OPERATORAccess().getLtAssignment_1(), "rule__REL_OPERATOR__LtAssignment_1");
			builder.put(grammarAccess.getREL_OPERATORAccess().getEqAssignment_2(), "rule__REL_OPERATOR__EqAssignment_2");
			builder.put(grammarAccess.getREL_OPERATORAccess().getNeAssignment_3(), "rule__REL_OPERATOR__NeAssignment_3");
			builder.put(grammarAccess.getREL_OPERATORAccess().getLeAssignment_4(), "rule__REL_OPERATOR__LeAssignment_4");
			builder.put(grammarAccess.getREL_OPERATORAccess().getGeAssignment_5(), "rule__REL_OPERATOR__GeAssignment_5");
			builder.put(grammarAccess.getNumberAccess().getNegativeAssignment_0_1(), "rule__Number__NegativeAssignment_0_1");
			builder.put(grammarAccess.getNumberAccess().getRealAssignment_1(), "rule__Number__RealAssignment_1");
			builder.put(grammarAccess.getNumberAccess().getDecimalAssignment_2_0_0(), "rule__Number__DecimalAssignment_2_0_0");
			builder.put(grammarAccess.getNumberAccess().getDecimalPartAssignment_2_0_1(), "rule__Number__DecimalPartAssignment_2_0_1");
			builder.put(grammarAccess.getNumberAccess().getExponentialAssignment_3_0_0(), "rule__Number__ExponentialAssignment_3_0_0");
			builder.put(grammarAccess.getNumberAccess().getExpNegativeAssignment_3_0_1_1(), "rule__Number__ExpNegativeAssignment_3_0_1_1");
			builder.put(grammarAccess.getNumberAccess().getExpAssignment_3_0_2(), "rule__Number__ExpAssignment_3_0_2");
			builder.put(grammarAccess.getModelAccess().getUnorderedGroup_0(), "rule__Model__UnorderedGroup_0");
			builder.put(grammarAccess.getActorDefinitionAccess().getUnorderedGroup_1_16(), "rule__ActorDefinition__UnorderedGroup_1_16");
			builder.put(grammarAccess.getDataflowBodyAccess().getUnorderedGroup_2(), "rule__DataflowBody__UnorderedGroup_2");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private KdlGrammarAccess grammarAccess;

	@Override
	protected InternalKdlParser createParser() {
		InternalKdlParser result = new InternalKdlParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public KdlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(KdlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
