server:
   port: 8287
   servlet:
     contextPath: "/node"

spring:
  servlet:
     multipart:
       enabled: true
       max-file-size: -1
       max-request-size: -1
      
klab:
   node:
      submitting: "*"
      searching: "*"
   adapter:
      fscan:
         auth: "*"
      stats:
         auth: "*"
      raster:
         auth: "*"
      vector:
         auth: "*"
      wcs:
         auth: "*"
      weather:
         auth: "*"
      wfs:
         auth: "*"
      copernicus:
         auth: "*"
   geoserver:
      password: geoserver
      url: http://127.0.0.1:8080/geoserver
      user: admin
   postgres:
      host: localhost
      password: password
      port: 5432
      user: postgres
