/**
 * generated by Xtext 2.19.0
 */
package org.integratedmodelling.kap.ui.contentassist;

import org.integratedmodelling.kap.ui.contentassist.AbstractKapProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class KapProposalProvider extends AbstractKapProposalProvider {
}
