= Developer API: using and extending k.LAB from code
:doctype: book
ifndef::sourcedir[:sourcedir: ../../../main/java]

Overview...

== Embedding a k.LAB engine

A programmer can use the engine API to embed observation functionalities in JVM-compatible programs. In order to do so, the k.LAB code must be imported. As k.LAB is in Maven Central, the simplest way to do so is through Maven or Gradle:

[source,xml]
----
		<dependency>
			<groupId>org.integratedmodelling</groupId>
			<artifactId>klab.modeler</artifactId>
			<!-- define or substitute the klab.version variable 
			     with the most recent version -->
			<version>${klab.version}</version> 
		</dependency>
----

There are several modules in the k.LAB source stack, but the `klab.modeler` dependency should be all you need to follow the examples in this documentation. A note of caution: this will import a _lot_ of code through transitive dependencies. As much as we appreciate single-jar software components, there is simply no way to build anything like this from scratch! 

If, instead, what you desire is to set up a development environment with the k.LAB source code, to explore, study or (bless you) contribute, follow the instructions <<TBD,here>>.

A basic example of using the Java API to access the network and make observations through referencing concept and observation URNs could look like this:

[source,java]
----
Engine engine = Engine.start();

try (ISession session = engine.createSession()) {

  IObservation observation =
    session
      // ISession.observe(urn) returns a future ISubject
      .observe("im:ariesteam:example.locations:tanzania>>earth:Region").get()
      /* ISubject.observe(urn) will return a future IObservation, in this case
         a IState (observation of a quality within the subject) */
      .observe("geography:Elevation").get();

    /* visualize in k.Explorer (opens a browser window). This
       displays the entire observation tree, focused on the caller. */
    observation.explore();

} finally {
    engine.stop();
}
----

The first call creates and boots a modeling engine, of which you will only need one:

This uses the default configuration, looking for a file named `im.cert` in the default 
k.LAB work directory (`~/.klab`), containing a valid k.LAB  certificate. You can use a 
specific certificate, and change a number of other settings, by passing an appropriately configured `EngineStartupOptions` object as a parameter to the `Engine.start()` call.

In all cases, the initialization method called on the engine will authorize the user, synchronize the user's assigned worldview from the network, load it, connect to the k.LAB network through the nearest k.LAB hub, and initialize all network resources according to the user's permissions. When that exits (after a short wait) without error, the engine is ready to make observations. The engine makes observations within a *session*, which we must request. User operations and API requests are assumed synchronous within a session, while concurrent sessions coexist without problems.

A Session is a `java.io.Closeable` so it can be opened and closed automatically within a try-with-resource block:

[source,java]
----
try (ISession session = engine.createSession()) {
   // ...make observations within the session
} finally {
   // you can call engine.stop() here if you're done. The session is closed automatically.
   // Alternatively, you can call session.close() yourself.
}
----

The rationale of having sessions is that an engine can serve multiple simultaneous sessions, owned by different users. In fact, createSession() can be optionally passed a previously authenticated  IUser, which the web interface of the k.LAB engine allows to configure and authenticate. In  embedded mode, we can simply use the shorthand method createSession() with no arguments, which  will create a session owned by the same user who owns the engine and the certificate. You can retrieve this user from the engine using `engine.getUser()`.

== A developer's guide to k.LAB

=== Service API

=== Project API

=== Ontology parsing, storing and reasoning

=== Resource API

==== Resource Adapter API

=== Observation API

==== Mediation and rescaling API

=== Observation geometry: space/time topologies

What is a topology, geometry, dimension, scale, extent and how they are implemented.

==== Locating and scanning geometries and scales

No matter the internal representation of the scale, all scaling eventually resolves to linear offsets that point to a particular location in storage. k.LAB implements a uniform strategy to resolve scales and geometries to their linear addresses. This is based on the ILocator interface, which is implemented by geometries and extents. Locators can be _adapted_ to other types using their `as(Class<?>)` method: the `Offset` locator is guaranteed to always be defined in such conversions. `Offset` can produce the `IGeometry` over which it is defined and, when used in a scalar fashion, the numeric offsets for each of its dimensions and overall.

By using the `Offset` locator, any locator can be resolved to the corresponding numeric offsets:

[source,java]
----

	// .... code receives a state and a grid Cell named cell
	Offset cellOffset = cell.as(Offset.class);
	// cellOffset now also contains the original geometry so knows the time, too
	long spaceOffset = cellOffset.getOffset(Dimension.Type.SPACE);
	long timeOffset = cellOffset.getOffset(Dimension.Type.TIME);

----


=== Storage providers

=== Runtime concepts

==== Authentication and connection to the k.LAB semantic web

==== Identities and Monitors

==== Sessions

==== Dataflow

==== Runtime execution

==== The actor system

==== Tracking provenance

=== Other modules in the k.LAB software stack

So far we have discussed the k.LAB engine. 

==== Languages: k.IM and k.DL

==== UI: the Explorer

==== The k.LAB hub

==== The k.LAB node

==== The k.LAB IDE (k.Modeler)

== The REST APIs

== Developing extensions

A major part of many independent developers’ interests will likely include development of `components` – independent packages that provide functionalities for k.LAB, such as new model integrations. A  Maven archetype is provided that installs a sample component to use as a template. The https://github.com/integratedmodelling/klab[klab] project in Github contains the components that are currently distributed with the system.

Components can provide:

* *contextualizers*, which implement specific contextualization strategies for dataflows and can be called in k.IM as functions.
* *resource adapters*, which provide support for specific data formats or server-based computational strategies that are called in k.IM by referencing URNs whose contents can be hosted locally or published on servers.
* *language support* for a programming language to be usable within a k.IM expression block.

Of course, the entire k.LAB code base is open source and any serious developer who feels they can contribute to the core software is welcome to check it out, fork it, play with it and propose changes and improvements, according to the terms of the https://www.gnu.org/licenses/gpl-3.0.en.html[General Public License 3.0].

