= Developer API: using and extending k.LAB from code
:doctype: book
ifndef::sourcedir[:sourcedir: ../../../main/java]

Overview...

== Embedding a k.LAB engine

A programmer can use the engine API to embed observation functionalities in JVM-compatible programs. A basic example of using the Java API to access the network and make observations through referencing concept and observation URNs could look like this:

[source,java]
----
Engine engine = Engine.start();

try (ISession session = engine.createSession()) {

  IObservation observation =
    session
      // ISession.observe(urn) returns a future ISubject
      .observe("im:ariesteam:example.locations:tanzania>>earth:Region").get()
      /* ISubject.observe(urn) will return a future IObservation, in this case
         a IState (observation of a quality within the subject) */
      .observe("geography:Elevation").get();

    /* visualize in k.Explorer (opens a browser window). This
       displays the entire observation tree, focused on the caller. */
    observation.explore();

} finally {
    engine.stop();
}
----

The first call creates and boots a modeling engine, of which you will only need one:

This uses the default configuration, looking for a file named `im.cert` in the default 
k.LAB work directory (`~/.klab`), containing a valid k.LAB  certificate. You can use a 
specific certificate, and change a number of other settings, by passing an appropriately configured `EngineStartupOptions` object as a parameter to the `Engine.start()` call.

In all cases, the initialization method called on the engine will authorize the user, synchronize the user's assigned worldview from the network, load it, connect to the k.LAB network through the nearest k.LAB hub, and initialize all network resources according to the user's permissions. When that exits (after a short wait) without error, the engine is ready to make observations. The engine makes observations within a *session*, which we must request. User operations and API requests are assumed synchronous within a session, while concurrent sessions coexist without problems.

A Session is a `java.io.Closeable` so it can be opened and closed automatically within a try-with-resource block:

[source,java]
----
try (ISession session = engine.createSession()) {
   // ...make observations within the session
} finally {
   // you can call engine.stop() here if you're done. The session is closed automatically.
   // Alternatively, you can call session.close() yourself.
}
----

The rationale of having sessions is that an engine can serve multiple simultaneous sessions, owned by different users. In fact, createSession() can be optionally passed a previously authenticated  IUser, which the web interface of the k.LAB engine allows to configure and authenticate. In  embedded mode, we can simply use the shorthand method createSession() with no arguments, which  will create a session owned by the same user who owns the engine and the certificate. You can retrieve this user from the engine using `engine.getUser()`.

== A field guide to the k.LAB source code

== Using the REST API

== Developing extensions

A major part of many independent developers’ interests will likely include development of `components` – independent packages that provide functionalities for k.LAB, such as new model integrations. A  Maven archetype is provided that installs a sample component to use as a template. The `klab` project in Bitbucket contains many of the components that are currently available.

Components can provide:

* *contextualizers*, which implement specific contextualization strategies for dataflows and can be called in k.IM as functions.
* *resource adapters*, which provide support for specific data formats or server-based computational strategies that are called in k.IM by referencing URNs whose contents can be hosted locally or published on servers.
* *language support* for a programming language to be usable within a k.IM expression block.

Of course, the entire k.LAB code base is open source and any serious developer who feels they can contribute to the core software is welcome to check it out, fork it, play with it and propose changes and improvements, according to the terms of the https://www.gnu.org/licenses/gpl-3.0.en.html[General Public License 3.0].
 
