/*
 * generated by Xtext 2.27.0
 */
package org.integratedmodelling.kdl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.integratedmodelling.kdl.parser.antlr.internal.InternalKdlParser;
import org.integratedmodelling.kdl.services.KdlGrammarAccess;

public class KdlParser extends AbstractAntlrParser {

	@Inject
	private KdlGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalKdlParser createParser(XtextTokenStream stream) {
		return new InternalKdlParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public KdlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(KdlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
