/**
 * Copyright (C) 2009-2016 integratedmodelling.org
 * generated by Xtext 2.26.0
 */
package org.integratedmodelling.kim.kim;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Doc Selector</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.integratedmodelling.kim.kim.DocSelector#getId <em>Id</em>}</li>
 *   <li>{@link org.integratedmodelling.kim.kim.DocSelector#isDefinition <em>Definition</em>}</li>
 *   <li>{@link org.integratedmodelling.kim.kim.DocSelector#isInitialization <em>Initialization</em>}</li>
 *   <li>{@link org.integratedmodelling.kim.kim.DocSelector#isTermination <em>Termination</em>}</li>
 *   <li>{@link org.integratedmodelling.kim.kim.DocSelector#isTransition <em>Transition</em>}</li>
 * </ul>
 *
 * @see org.integratedmodelling.kim.kim.KimPackage#getDocSelector()
 * @model
 * @generated
 */
public interface DocSelector extends EObject
{
  /**
   * Returns the value of the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' attribute.
   * @see #setId(String)
   * @see org.integratedmodelling.kim.kim.KimPackage#getDocSelector_Id()
   * @model
   * @generated
   */
  String getId();

  /**
   * Sets the value of the '{@link org.integratedmodelling.kim.kim.DocSelector#getId <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' attribute.
   * @see #getId()
   * @generated
   */
  void setId(String value);

  /**
   * Returns the value of the '<em><b>Definition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Definition</em>' attribute.
   * @see #setDefinition(boolean)
   * @see org.integratedmodelling.kim.kim.KimPackage#getDocSelector_Definition()
   * @model
   * @generated
   */
  boolean isDefinition();

  /**
   * Sets the value of the '{@link org.integratedmodelling.kim.kim.DocSelector#isDefinition <em>Definition</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Definition</em>' attribute.
   * @see #isDefinition()
   * @generated
   */
  void setDefinition(boolean value);

  /**
   * Returns the value of the '<em><b>Initialization</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Initialization</em>' attribute.
   * @see #setInitialization(boolean)
   * @see org.integratedmodelling.kim.kim.KimPackage#getDocSelector_Initialization()
   * @model
   * @generated
   */
  boolean isInitialization();

  /**
   * Sets the value of the '{@link org.integratedmodelling.kim.kim.DocSelector#isInitialization <em>Initialization</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Initialization</em>' attribute.
   * @see #isInitialization()
   * @generated
   */
  void setInitialization(boolean value);

  /**
   * Returns the value of the '<em><b>Termination</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Termination</em>' attribute.
   * @see #setTermination(boolean)
   * @see org.integratedmodelling.kim.kim.KimPackage#getDocSelector_Termination()
   * @model
   * @generated
   */
  boolean isTermination();

  /**
   * Sets the value of the '{@link org.integratedmodelling.kim.kim.DocSelector#isTermination <em>Termination</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Termination</em>' attribute.
   * @see #isTermination()
   * @generated
   */
  void setTermination(boolean value);

  /**
   * Returns the value of the '<em><b>Transition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Transition</em>' attribute.
   * @see #setTransition(boolean)
   * @see org.integratedmodelling.kim.kim.KimPackage#getDocSelector_Transition()
   * @model
   * @generated
   */
  boolean isTransition();

  /**
   * Sets the value of the '{@link org.integratedmodelling.kim.kim.DocSelector#isTransition <em>Transition</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Transition</em>' attribute.
   * @see #isTransition()
   * @generated
   */
  void setTransition(boolean value);

} // DocSelector
