/**
 * Copyright (C) 2009-2016 integratedmodelling.org
 * generated by Xtext 2.27.0
 */
package org.integratedmodelling.kim.kim;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model Body Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.integratedmodelling.kim.kim.ModelBodyStatement#isInstantiator <em>Instantiator</em>}</li>
 *   <li>{@link org.integratedmodelling.kim.kim.ModelBodyStatement#getUrns <em>Urns</em>}</li>
 *   <li>{@link org.integratedmodelling.kim.kim.ModelBodyStatement#getNumber <em>Number</em>}</li>
 *   <li>{@link org.integratedmodelling.kim.kim.ModelBodyStatement#getConcept <em>Concept</em>}</li>
 *   <li>{@link org.integratedmodelling.kim.kim.ModelBodyStatement#getBoolean <em>Boolean</em>}</li>
 *   <li>{@link org.integratedmodelling.kim.kim.ModelBodyStatement#getName <em>Name</em>}</li>
 *   <li>{@link org.integratedmodelling.kim.kim.ModelBodyStatement#getObservables <em>Observables</em>}</li>
 *   <li>{@link org.integratedmodelling.kim.kim.ModelBodyStatement#getDocstring <em>Docstring</em>}</li>
 *   <li>{@link org.integratedmodelling.kim.kim.ModelBodyStatement#getDependencies <em>Dependencies</em>}</li>
 *   <li>{@link org.integratedmodelling.kim.kim.ModelBodyStatement#getContextualizers <em>Contextualizers</em>}</li>
 *   <li>{@link org.integratedmodelling.kim.kim.ModelBodyStatement#isDiscretization <em>Discretization</em>}</li>
 *   <li>{@link org.integratedmodelling.kim.kim.ModelBodyStatement#getClassification <em>Classification</em>}</li>
 *   <li>{@link org.integratedmodelling.kim.kim.ModelBodyStatement#getClassificationProperty <em>Classification Property</em>}</li>
 *   <li>{@link org.integratedmodelling.kim.kim.ModelBodyStatement#getLookupTableArgs <em>Lookup Table Args</em>}</li>
 *   <li>{@link org.integratedmodelling.kim.kim.ModelBodyStatement#getLookupTable <em>Lookup Table</em>}</li>
 *   <li>{@link org.integratedmodelling.kim.kim.ModelBodyStatement#getLookupTableId <em>Lookup Table Id</em>}</li>
 *   <li>{@link org.integratedmodelling.kim.kim.ModelBodyStatement#isTwoway <em>Twoway</em>}</li>
 *   <li>{@link org.integratedmodelling.kim.kim.ModelBodyStatement#getActions <em>Actions</em>}</li>
 *   <li>{@link org.integratedmodelling.kim.kim.ModelBodyStatement#getMetadata <em>Metadata</em>}</li>
 * </ul>
 *
 * @see org.integratedmodelling.kim.kim.KimPackage#getModelBodyStatement()
 * @model
 * @generated
 */
public interface ModelBodyStatement extends EObject
{
  /**
   * Returns the value of the '<em><b>Instantiator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Instantiator</em>' attribute.
   * @see #setInstantiator(boolean)
   * @see org.integratedmodelling.kim.kim.KimPackage#getModelBodyStatement_Instantiator()
   * @model
   * @generated
   */
  boolean isInstantiator();

  /**
   * Sets the value of the '{@link org.integratedmodelling.kim.kim.ModelBodyStatement#isInstantiator <em>Instantiator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Instantiator</em>' attribute.
   * @see #isInstantiator()
   * @generated
   */
  void setInstantiator(boolean value);

  /**
   * Returns the value of the '<em><b>Urns</b></em>' containment reference list.
   * The list contents are of type {@link org.integratedmodelling.kim.kim.Urn}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Urns</em>' containment reference list.
   * @see org.integratedmodelling.kim.kim.KimPackage#getModelBodyStatement_Urns()
   * @model containment="true"
   * @generated
   */
  EList<Urn> getUrns();

  /**
   * Returns the value of the '<em><b>Number</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Number</em>' containment reference.
   * @see #setNumber(org.integratedmodelling.kim.kim.Number)
   * @see org.integratedmodelling.kim.kim.KimPackage#getModelBodyStatement_Number()
   * @model containment="true"
   * @generated
   */
  org.integratedmodelling.kim.kim.Number getNumber();

  /**
   * Sets the value of the '{@link org.integratedmodelling.kim.kim.ModelBodyStatement#getNumber <em>Number</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Number</em>' containment reference.
   * @see #getNumber()
   * @generated
   */
  void setNumber(org.integratedmodelling.kim.kim.Number value);

  /**
   * Returns the value of the '<em><b>Concept</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Concept</em>' containment reference.
   * @see #setConcept(ConceptDeclaration)
   * @see org.integratedmodelling.kim.kim.KimPackage#getModelBodyStatement_Concept()
   * @model containment="true"
   * @generated
   */
  ConceptDeclaration getConcept();

  /**
   * Sets the value of the '{@link org.integratedmodelling.kim.kim.ModelBodyStatement#getConcept <em>Concept</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Concept</em>' containment reference.
   * @see #getConcept()
   * @generated
   */
  void setConcept(ConceptDeclaration value);

  /**
   * Returns the value of the '<em><b>Boolean</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Boolean</em>' attribute.
   * @see #setBoolean(String)
   * @see org.integratedmodelling.kim.kim.KimPackage#getModelBodyStatement_Boolean()
   * @model
   * @generated
   */
  String getBoolean();

  /**
   * Sets the value of the '{@link org.integratedmodelling.kim.kim.ModelBodyStatement#getBoolean <em>Boolean</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Boolean</em>' attribute.
   * @see #getBoolean()
   * @generated
   */
  void setBoolean(String value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.integratedmodelling.kim.kim.KimPackage#getModelBodyStatement_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.integratedmodelling.kim.kim.ModelBodyStatement#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Observables</b></em>' containment reference list.
   * The list contents are of type {@link org.integratedmodelling.kim.kim.ObservableSemantics}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Observables</em>' containment reference list.
   * @see org.integratedmodelling.kim.kim.KimPackage#getModelBodyStatement_Observables()
   * @model containment="true"
   * @generated
   */
  EList<ObservableSemantics> getObservables();

  /**
   * Returns the value of the '<em><b>Docstring</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Docstring</em>' attribute.
   * @see #setDocstring(String)
   * @see org.integratedmodelling.kim.kim.KimPackage#getModelBodyStatement_Docstring()
   * @model
   * @generated
   */
  String getDocstring();

  /**
   * Sets the value of the '{@link org.integratedmodelling.kim.kim.ModelBodyStatement#getDocstring <em>Docstring</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Docstring</em>' attribute.
   * @see #getDocstring()
   * @generated
   */
  void setDocstring(String value);

  /**
   * Returns the value of the '<em><b>Dependencies</b></em>' containment reference list.
   * The list contents are of type {@link org.integratedmodelling.kim.kim.Dependency}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dependencies</em>' containment reference list.
   * @see org.integratedmodelling.kim.kim.KimPackage#getModelBodyStatement_Dependencies()
   * @model containment="true"
   * @generated
   */
  EList<Dependency> getDependencies();

  /**
   * Returns the value of the '<em><b>Contextualizers</b></em>' containment reference list.
   * The list contents are of type {@link org.integratedmodelling.kim.kim.ValueAssignment}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Contextualizers</em>' containment reference list.
   * @see org.integratedmodelling.kim.kim.KimPackage#getModelBodyStatement_Contextualizers()
   * @model containment="true"
   * @generated
   */
  EList<ValueAssignment> getContextualizers();

  /**
   * Returns the value of the '<em><b>Discretization</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Discretization</em>' attribute.
   * @see #setDiscretization(boolean)
   * @see org.integratedmodelling.kim.kim.KimPackage#getModelBodyStatement_Discretization()
   * @model
   * @generated
   */
  boolean isDiscretization();

  /**
   * Sets the value of the '{@link org.integratedmodelling.kim.kim.ModelBodyStatement#isDiscretization <em>Discretization</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Discretization</em>' attribute.
   * @see #isDiscretization()
   * @generated
   */
  void setDiscretization(boolean value);

  /**
   * Returns the value of the '<em><b>Classification</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Classification</em>' containment reference.
   * @see #setClassification(Classification)
   * @see org.integratedmodelling.kim.kim.KimPackage#getModelBodyStatement_Classification()
   * @model containment="true"
   * @generated
   */
  Classification getClassification();

  /**
   * Sets the value of the '{@link org.integratedmodelling.kim.kim.ModelBodyStatement#getClassification <em>Classification</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Classification</em>' containment reference.
   * @see #getClassification()
   * @generated
   */
  void setClassification(Classification value);

  /**
   * Returns the value of the '<em><b>Classification Property</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Classification Property</em>' attribute.
   * @see #setClassificationProperty(String)
   * @see org.integratedmodelling.kim.kim.KimPackage#getModelBodyStatement_ClassificationProperty()
   * @model
   * @generated
   */
  String getClassificationProperty();

  /**
   * Sets the value of the '{@link org.integratedmodelling.kim.kim.ModelBodyStatement#getClassificationProperty <em>Classification Property</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Classification Property</em>' attribute.
   * @see #getClassificationProperty()
   * @generated
   */
  void setClassificationProperty(String value);

  /**
   * Returns the value of the '<em><b>Lookup Table Args</b></em>' containment reference list.
   * The list contents are of type {@link org.integratedmodelling.kim.kim.LookupTableArgument}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lookup Table Args</em>' containment reference list.
   * @see org.integratedmodelling.kim.kim.KimPackage#getModelBodyStatement_LookupTableArgs()
   * @model containment="true"
   * @generated
   */
  EList<LookupTableArgument> getLookupTableArgs();

  /**
   * Returns the value of the '<em><b>Lookup Table</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lookup Table</em>' containment reference.
   * @see #setLookupTable(Table)
   * @see org.integratedmodelling.kim.kim.KimPackage#getModelBodyStatement_LookupTable()
   * @model containment="true"
   * @generated
   */
  Table getLookupTable();

  /**
   * Sets the value of the '{@link org.integratedmodelling.kim.kim.ModelBodyStatement#getLookupTable <em>Lookup Table</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lookup Table</em>' containment reference.
   * @see #getLookupTable()
   * @generated
   */
  void setLookupTable(Table value);

  /**
   * Returns the value of the '<em><b>Lookup Table Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lookup Table Id</em>' attribute.
   * @see #setLookupTableId(String)
   * @see org.integratedmodelling.kim.kim.KimPackage#getModelBodyStatement_LookupTableId()
   * @model
   * @generated
   */
  String getLookupTableId();

  /**
   * Sets the value of the '{@link org.integratedmodelling.kim.kim.ModelBodyStatement#getLookupTableId <em>Lookup Table Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lookup Table Id</em>' attribute.
   * @see #getLookupTableId()
   * @generated
   */
  void setLookupTableId(String value);

  /**
   * Returns the value of the '<em><b>Twoway</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Twoway</em>' attribute.
   * @see #setTwoway(boolean)
   * @see org.integratedmodelling.kim.kim.KimPackage#getModelBodyStatement_Twoway()
   * @model
   * @generated
   */
  boolean isTwoway();

  /**
   * Sets the value of the '{@link org.integratedmodelling.kim.kim.ModelBodyStatement#isTwoway <em>Twoway</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Twoway</em>' attribute.
   * @see #isTwoway()
   * @generated
   */
  void setTwoway(boolean value);

  /**
   * Returns the value of the '<em><b>Actions</b></em>' containment reference list.
   * The list contents are of type {@link org.integratedmodelling.kim.kim.ActionSpecification}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Actions</em>' containment reference list.
   * @see org.integratedmodelling.kim.kim.KimPackage#getModelBodyStatement_Actions()
   * @model containment="true"
   * @generated
   */
  EList<ActionSpecification> getActions();

  /**
   * Returns the value of the '<em><b>Metadata</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Metadata</em>' containment reference.
   * @see #setMetadata(Map)
   * @see org.integratedmodelling.kim.kim.KimPackage#getModelBodyStatement_Metadata()
   * @model containment="true"
   * @generated
   */
  Map getMetadata();

  /**
   * Sets the value of the '{@link org.integratedmodelling.kim.kim.ModelBodyStatement#getMetadata <em>Metadata</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Metadata</em>' containment reference.
   * @see #getMetadata()
   * @generated
   */
  void setMetadata(Map value);

} // ModelBodyStatement
