/**
 * Copyright (C) 2009-2016 integratedmodelling.org
 * generated by Xtext 2.27.0
 */
package org.integratedmodelling.kim.kim;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Value Assignment</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.integratedmodelling.kim.kim.ValueAssignment#getTarget <em>Target</em>}</li>
 *   <li>{@link org.integratedmodelling.kim.kim.ValueAssignment#getAssignedValue <em>Assigned Value</em>}</li>
 *   <li>{@link org.integratedmodelling.kim.kim.ValueAssignment#getExecValue <em>Exec Value</em>}</li>
 * </ul>
 *
 * @see org.integratedmodelling.kim.kim.KimPackage#getValueAssignment()
 * @model
 * @generated
 */
public interface ValueAssignment extends EObject
{
  /**
   * Returns the value of the '<em><b>Target</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' attribute.
   * @see #setTarget(String)
   * @see org.integratedmodelling.kim.kim.KimPackage#getValueAssignment_Target()
   * @model
   * @generated
   */
  String getTarget();

  /**
   * Sets the value of the '{@link org.integratedmodelling.kim.kim.ValueAssignment#getTarget <em>Target</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' attribute.
   * @see #getTarget()
   * @generated
   */
  void setTarget(String value);

  /**
   * Returns the value of the '<em><b>Assigned Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Assigned Value</em>' containment reference.
   * @see #setAssignedValue(ComputableValue)
   * @see org.integratedmodelling.kim.kim.KimPackage#getValueAssignment_AssignedValue()
   * @model containment="true"
   * @generated
   */
  ComputableValue getAssignedValue();

  /**
   * Sets the value of the '{@link org.integratedmodelling.kim.kim.ValueAssignment#getAssignedValue <em>Assigned Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Assigned Value</em>' containment reference.
   * @see #getAssignedValue()
   * @generated
   */
  void setAssignedValue(ComputableValue value);

  /**
   * Returns the value of the '<em><b>Exec Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exec Value</em>' containment reference.
   * @see #setExecValue(ComputableValue)
   * @see org.integratedmodelling.kim.kim.KimPackage#getValueAssignment_ExecValue()
   * @model containment="true"
   * @generated
   */
  ComputableValue getExecValue();

  /**
   * Sets the value of the '{@link org.integratedmodelling.kim.kim.ValueAssignment#getExecValue <em>Exec Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exec Value</em>' containment reference.
   * @see #getExecValue()
   * @generated
   */
  void setExecValue(ComputableValue value);

} // ValueAssignment
