/**
 * generated by Xtext 2.19.0
 */
package org.integratedmodelling.kactors.kactors;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Assert Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.integratedmodelling.kactors.kactors.AssertStatement#getMethodCalls <em>Method Calls</em>}</li>
 * </ul>
 *
 * @see org.integratedmodelling.kactors.kactors.KactorsPackage#getAssertStatement()
 * @model
 * @generated
 */
public interface AssertStatement extends EObject
{
  /**
   * Returns the value of the '<em><b>Method Calls</b></em>' containment reference list.
   * The list contents are of type {@link org.integratedmodelling.kactors.kactors.MessageCall}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Method Calls</em>' containment reference list.
   * @see org.integratedmodelling.kactors.kactors.KactorsPackage#getAssertStatement_MethodCalls()
   * @model containment="true"
   * @generated
   */
  EList<MessageCall> getMethodCalls();

} // AssertStatement
