/**
 * generated by Xtext 2.27.0
 */
package org.integratedmodelling.kactors.kactors;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Statement List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.integratedmodelling.kactors.kactors.StatementList#getFirst <em>First</em>}</li>
 *   <li>{@link org.integratedmodelling.kactors.kactors.StatementList#getNext <em>Next</em>}</li>
 * </ul>
 *
 * @see org.integratedmodelling.kactors.kactors.KactorsPackage#getStatementList()
 * @model
 * @generated
 */
public interface StatementList extends EObject
{
  /**
   * Returns the value of the '<em><b>First</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>First</em>' containment reference.
   * @see #setFirst(Statement)
   * @see org.integratedmodelling.kactors.kactors.KactorsPackage#getStatementList_First()
   * @model containment="true"
   * @generated
   */
  Statement getFirst();

  /**
   * Sets the value of the '{@link org.integratedmodelling.kactors.kactors.StatementList#getFirst <em>First</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>First</em>' containment reference.
   * @see #getFirst()
   * @generated
   */
  void setFirst(Statement value);

  /**
   * Returns the value of the '<em><b>Next</b></em>' containment reference list.
   * The list contents are of type {@link org.integratedmodelling.kactors.kactors.Statement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Next</em>' containment reference list.
   * @see org.integratedmodelling.kactors.kactors.KactorsPackage#getStatementList_Next()
   * @model containment="true"
   * @generated
   */
  EList<Statement> getNext();

} // StatementList
