/**
 * generated by Xtext 2.12.0
 */
package org.integratedmodelling.kdl.kdl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.integratedmodelling.kdl.kdl.Value#getLiteral <em>Literal</em>}</li>
 *   <li>{@link org.integratedmodelling.kdl.kdl.Value#getFunction <em>Function</em>}</li>
 *   <li>{@link org.integratedmodelling.kdl.kdl.Value#getUrn <em>Urn</em>}</li>
 *   <li>{@link org.integratedmodelling.kdl.kdl.Value#getUnit <em>Unit</em>}</li>
 *   <li>{@link org.integratedmodelling.kdl.kdl.Value#getCurrency <em>Currency</em>}</li>
 *   <li>{@link org.integratedmodelling.kdl.kdl.Value#getList <em>List</em>}</li>
 *   <li>{@link org.integratedmodelling.kdl.kdl.Value#getEnumId <em>Enum Id</em>}</li>
 * </ul>
 *
 * @see org.integratedmodelling.kdl.kdl.KdlPackage#getValue()
 * @model
 * @generated
 */
public interface Value extends EObject
{
  /**
   * Returns the value of the '<em><b>Literal</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Literal</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Literal</em>' containment reference.
   * @see #setLiteral(Literal)
   * @see org.integratedmodelling.kdl.kdl.KdlPackage#getValue_Literal()
   * @model containment="true"
   * @generated
   */
  Literal getLiteral();

  /**
   * Sets the value of the '{@link org.integratedmodelling.kdl.kdl.Value#getLiteral <em>Literal</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Literal</em>' containment reference.
   * @see #getLiteral()
   * @generated
   */
  void setLiteral(Literal value);

  /**
   * Returns the value of the '<em><b>Function</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Function</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Function</em>' containment reference.
   * @see #setFunction(Function)
   * @see org.integratedmodelling.kdl.kdl.KdlPackage#getValue_Function()
   * @model containment="true"
   * @generated
   */
  Function getFunction();

  /**
   * Sets the value of the '{@link org.integratedmodelling.kdl.kdl.Value#getFunction <em>Function</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Function</em>' containment reference.
   * @see #getFunction()
   * @generated
   */
  void setFunction(Function value);

  /**
   * Returns the value of the '<em><b>Urn</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Urn</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Urn</em>' containment reference.
   * @see #setUrn(Urn)
   * @see org.integratedmodelling.kdl.kdl.KdlPackage#getValue_Urn()
   * @model containment="true"
   * @generated
   */
  Urn getUrn();

  /**
   * Sets the value of the '{@link org.integratedmodelling.kdl.kdl.Value#getUrn <em>Urn</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Urn</em>' containment reference.
   * @see #getUrn()
   * @generated
   */
  void setUrn(Urn value);

  /**
   * Returns the value of the '<em><b>Unit</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Unit</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unit</em>' containment reference.
   * @see #setUnit(Unit)
   * @see org.integratedmodelling.kdl.kdl.KdlPackage#getValue_Unit()
   * @model containment="true"
   * @generated
   */
  Unit getUnit();

  /**
   * Sets the value of the '{@link org.integratedmodelling.kdl.kdl.Value#getUnit <em>Unit</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unit</em>' containment reference.
   * @see #getUnit()
   * @generated
   */
  void setUnit(Unit value);

  /**
   * Returns the value of the '<em><b>Currency</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Currency</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Currency</em>' containment reference.
   * @see #setCurrency(Currency)
   * @see org.integratedmodelling.kdl.kdl.KdlPackage#getValue_Currency()
   * @model containment="true"
   * @generated
   */
  Currency getCurrency();

  /**
   * Sets the value of the '{@link org.integratedmodelling.kdl.kdl.Value#getCurrency <em>Currency</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Currency</em>' containment reference.
   * @see #getCurrency()
   * @generated
   */
  void setCurrency(Currency value);

  /**
   * Returns the value of the '<em><b>List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>List</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>List</em>' containment reference.
   * @see #setList(List)
   * @see org.integratedmodelling.kdl.kdl.KdlPackage#getValue_List()
   * @model containment="true"
   * @generated
   */
  List getList();

  /**
   * Sets the value of the '{@link org.integratedmodelling.kdl.kdl.Value#getList <em>List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>List</em>' containment reference.
   * @see #getList()
   * @generated
   */
  void setList(List value);

  /**
   * Returns the value of the '<em><b>Enum Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Enum Id</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Enum Id</em>' attribute.
   * @see #setEnumId(String)
   * @see org.integratedmodelling.kdl.kdl.KdlPackage#getValue_EnumId()
   * @model
   * @generated
   */
  String getEnumId();

  /**
   * Sets the value of the '{@link org.integratedmodelling.kdl.kdl.Value#getEnumId <em>Enum Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Enum Id</em>' attribute.
   * @see #getEnumId()
   * @generated
   */
  void setEnumId(String value);

} // Value
