/**
 * Copyright (C) 2009-2016 integratedmodelling.org
 * generated by Xtext 2.12.0
 */
package org.integratedmodelling.kim.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.integratedmodelling.kim.KnowledgeDeclarationRuntimeModule;
import org.integratedmodelling.kim.KnowledgeDeclarationStandaloneSetup;
import org.integratedmodelling.kim.ide.KnowledgeDeclarationIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class KnowledgeDeclarationIdeSetup extends KnowledgeDeclarationStandaloneSetup {
  @Override
  public Injector createInjector() {
    KnowledgeDeclarationRuntimeModule _knowledgeDeclarationRuntimeModule = new KnowledgeDeclarationRuntimeModule();
    KnowledgeDeclarationIdeModule _knowledgeDeclarationIdeModule = new KnowledgeDeclarationIdeModule();
    return Guice.createInjector(Modules2.mixin(_knowledgeDeclarationRuntimeModule, _knowledgeDeclarationIdeModule));
  }
}
