/**
 * Copyright (C) 2009-2016 integratedmodelling.org
 * generated by Xtext 2.12.0
 */
package org.integratedmodelling.kim.kdecl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Unit</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.integratedmodelling.kim.kdecl.Unit#getRoot <em>Root</em>}</li>
 *   <li>{@link org.integratedmodelling.kim.kdecl.Unit#getConnectors <em>Connectors</em>}</li>
 *   <li>{@link org.integratedmodelling.kim.kdecl.Unit#getUnits <em>Units</em>}</li>
 * </ul>
 *
 * @see org.integratedmodelling.kim.kdecl.KdeclPackage#getUnit()
 * @model
 * @generated
 */
public interface Unit extends EObject
{
  /**
   * Returns the value of the '<em><b>Root</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Root</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Root</em>' containment reference.
   * @see #setRoot(UnitElement)
   * @see org.integratedmodelling.kim.kdecl.KdeclPackage#getUnit_Root()
   * @model containment="true"
   * @generated
   */
  UnitElement getRoot();

  /**
   * Sets the value of the '{@link org.integratedmodelling.kim.kdecl.Unit#getRoot <em>Root</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Root</em>' containment reference.
   * @see #getRoot()
   * @generated
   */
  void setRoot(UnitElement value);

  /**
   * Returns the value of the '<em><b>Connectors</b></em>' attribute list.
   * The list contents are of type {@link org.integratedmodelling.kim.kdecl.UnitOp}.
   * The literals are from the enumeration {@link org.integratedmodelling.kim.kdecl.UnitOp}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Connectors</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Connectors</em>' attribute list.
   * @see org.integratedmodelling.kim.kdecl.UnitOp
   * @see org.integratedmodelling.kim.kdecl.KdeclPackage#getUnit_Connectors()
   * @model unique="false"
   * @generated
   */
  EList<UnitOp> getConnectors();

  /**
   * Returns the value of the '<em><b>Units</b></em>' containment reference list.
   * The list contents are of type {@link org.integratedmodelling.kim.kdecl.UnitElement}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Units</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Units</em>' containment reference list.
   * @see org.integratedmodelling.kim.kdecl.KdeclPackage#getUnit_Units()
   * @model containment="true"
   * @generated
   */
  EList<UnitElement> getUnits();

} // Unit
