[#chapter-odo]
= Ontology of Descriptions and Observations for Integrated Modelling (ODO-IM)
Ferdinando Villa
:doctype: book
:encoding: utf-8
:lang: en

- **License**: [CC-BY](http://creativecommons.org/licenses/by/3.0/)
- [**Bug reports and feature requests**](https://github.com/integratedmodelling/odo/issues)

The ODO-IM ontology is a core product developed and maintained by the [Integrated Modelling Partnership](http://www.integratedmodelling.org) (IMP). It specifies a view of the scientific process that can be implemented in software to support the IMP's goals of modular, distributed, semantically explicit and integrated scientific computing and modeling, according to the FAIR principles. In ODO-IM terminology:

- **Description**s are activities that produce scientific artifacts  describing a concept. Subclasses of Description specify scientific assertions, models and computational workflows (Definitions, see below).
- **Observation**s are the scientific artifacts themselves, resulting from instantiating a Description within the context of an acknowledged root observation. Each concrete Description is restricted to produce a specific type of Observation.
- **Observable**s hierarchy are the _concepts_ that provide the object of a Description and the subject of the resulting Observation. Observables can be combined with **Predicate**s (such as attributes, roles etc) in compliance with constraints specified as restrictions on ODO-IM properties. The ODO-IM adopts an *orthogonality* principle that implies that predicates are never subsumed directly in OWL classes defining observables. The main logical dimensions for observables are:

* Continuants vs. Occurrents nature (the only inevitable point of contact with core ontologies): ....
* Countability: ...
* ...

- The main logical dimensions for predicates are:
*  Identities
* Realms
* Roles
* Orderings
* Domains
* Attributes (which are not any of the above)

- **Definition**s are logical structures that can be used by an intelligent agent to carry out the Description of a specified Observable. Definitions specify observations either by acknowledgement (through an extensional statement) or by producing a computable dataflow (intensional statements listing zero or more Observables as dependencies). In ODO-IM applications, this class includes the main products of the activity of semantic modelling, i.e. what is commonly referred to as "data annotations" and "models". Properties and restrictions constrain specific classes of Definitions to specific classes of Observables.

ODO-IM is only concerned with observations and the activities that produce them, and does _not_ include logical statements that are included in upper ontologies and other observation ontologies. Specifically:

- It remains as agnostic as possible about the phenomenology of Observables, in an effort to preserve maximum orthogonality with an arbitrary upper ontology stated in a derived worldview. The characterization of Observables is intentionally shallow, as observables are meant to specialize types in an externally provided upper ontology to form the basis of a worldview. Such links are made in the root domain of the worldview. See the full documentation for minimum expressive requirements and caveats.
- It does not provide any detail on space, time and any other topologies implied in the definition of observational scale, beyond their statement as extentual observables (Extent), as their specific interpretation is left to worldviews derived from ODO-IM.
- It does not provide semantics for units of measurement, like other observation ontologies do. To support applications, ODO-IM only lists the SI base unit textually in annotation properties linked to all PhysicalProperty observables, using SI conventions. Applications can use any unit parser to translate these into data structures to support validation and conversion.

## Dependencies

ODO-IM only depends on the [PROV-O](https://www.w3.org/TR/prov-o/) provenance ontology, as Descriptions and Observations are, respectively, Activities (`prov:Activity`) and informational artifacts (`prov:Entity`).

## Rationale and Usage

The ODO-IM ontology is released under CC-BY license for any purpose. Its main rationale for existence is to serve as the semantic backbone of the *semantic meta-modeling* paradigm maintained by the IMP and operationalized through the k.LAB software stack. As part of this strategy, the k.IM language incarnates ODO-IM axioms in the syntax of a user-friendly language,  for which k.LAB provides intelligent editor support. The k.IM language allows its users to: 

- Define *worldviews* by specifying and composing Observables and Predicates, through efficient, flexible and readable statements, optimized for multi-domain, multi-scale definitions and with a built-in mechanisms for safe linking to existing controlled vocabularies. 
- Specify interoperable data annotations and computations (Definitions). The k.LAB software stack provides the infrastructure to publish such definitions, along with the resources they depend on, on networked repositories managed by specialized servers, and to peruse a federation of such servers to assemble context-specific computations that are run to generate Observations based on a user query for the corresponding Observable. 
	
Links to an upper ontology of choice are made in k.IM, in the root domain of each worldview, and are meant to support reasoning outside of k.LAB as the reasoning in k.LAB only depends on ODO-IM concepts. The k.LAB stack also includes a knowledge processor to rewrite k.IM namespaces into OWL ontologies and perform alignments, inference and other operations.

This repository is the official distribution of the ODO-IM ontology, whose latest master release is available as http://www.integratedmodelling.org/odo.owl. The docs/ directory contains source documentation in AsciiDoc. Pre-built documentation is available at http://www.integratedmodelling.org/docs/odo.