/**
 * generated by Xtext 2.19.0
 */
package org.integratedmodelling.kactors;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class KactorsStandaloneSetup extends KactorsStandaloneSetupGenerated {
  public static void doSetup() {
    new KactorsStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
