/**
 * generated by Xtext 2.12.0
 */
package org.integratedmodelling.kdl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.integratedmodelling.kdl.ui.AbstractKdlUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class KdlUiModule extends AbstractKdlUiModule {
  public KdlUiModule(final AbstractUIPlugin arg0) {
    super(arg0);
  }
}
