#%RAML 1.0
title: k.LAB Engine API
version: 0.10.0
protocols: [HTTP, HTTPS]
mediaType: application/json
documentation:
  - title: k.LAB Engine API documentation
    content: ZIO BOLLO
types:
  Capabilities: !include types/capabilities-schema.json
  AuthorizationRequest: !include types/authenticationRequest-schema.json
/capabilities:
  get:
    description: Get server capabilities. Public; response will change depending on authentication.
    responses:
      200:
        body:
          application/json:
            type: Capabilities
#            example: !include examples/capabilities-example.json
/ping:
  description: Check server status and time since boot.
  get:
    description: Number of milliseconds between server boot and time of call.
  head:
    description: Simplest HEAD call to check for response code. Intended for clients that need to do frequent heartbeat checking.
/schema:
  get:
    description: Retrieve the JSON v3 schema for the types used in the API, built on demand from the correspondent Java resources. Without parameters a map of all schemata is returned, indexed by the name of the correspondent resource.
